# .travis.yml - 2014-05-10 03:03
#
# Copyright (c) 2014 Paul Houghton <paul4hough@gmail.com>

language: ruby
notifications:
  email:
    - paul4hough@gmail.com

rvm:
 - 1.9.3
 - 2.0.0
env:
  matrix:
  - PUPPET_GEM_VERSION="~> 3.4.3"
  - PUPPET_GEM_VERSION="~> 3.5.1"
script: "bundle exec rake -t lint unittest_prep unittest_suite"
